spring.application.name=Drive

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
google.drive.folder.id=${GOOGLE_DRIVE_FOLDER_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

#File Storage Path
file.upload-dir=uploads/

# Max file size per request
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# oauth2 google & github
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.redirect-uri=https://drive-file-manager.onrender.com/login/oauth2/code/google
spring.security.oauth2.client.registration.github.redirect-uri=https://drive-file-manager.onrender.com/login/oauth2/code/github
server.forward-headers-strategy=framework

#refresh token
google.client.id=${GOOGLE_CLIENT_ID_REFRESH}
google.client.secret=${GOOGLE_CLIENT_SECRET_REFRESH}
google.refresh.token=${GOOGLE_REFRESH_TOKEN}


