# ---  APP SETTINGS (Common) ---
spring.application.name=DriveApp
# Render par iski zaroorat hoti hai
server.forward-headers-strategy=framework

# ---  FILE UPLOAD (Common) ---
# Dono jagah 500MB ki limit chahiye
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ---  DATABASE STRUCTURE (Common) ---
# TiDB/MySQL ke liye settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ---  HIKARICP (Performance - Common) ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ---  SECURITY (Common) ---
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# ---  DYNAMIC VARIABLES (Placeholders) ---
#Only name value pass in env
#spring.datasource.url=${TIDB_URL}
#spring.datasource.username=${TIDB_USER}
#spring.datasource.password=${TIDB_PASS}