spring.application.name=DriveApp
server.forward-headers-strategy=framework

# ---  FILE UPLOAD (Common) ---
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ---  HIKARICP (Performance - Common) ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ---  SECURITY (Common) ---

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true


spring.profiles.active=test


spring.datasource.url=${MYSQL_URL_PROD}
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}

# OAuth2 Google & GitHub
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID_PROD}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET_PROD}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID_PROD}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET_PROD}

#redirect:
spring.security.oauth2.client.registration.google.redirect-uri=https://drive-file-manager.onrender.com/login/oauth2/code/google
spring.security.oauth2.client.registration.github.redirect-uri=https://drive-file-manager.onrender.com/login/oauth2/code/github

google.drive.folder-id=${DRIVE_FOLDER_ID}
app.base-url=${APP_BASE_URL_PROD}

# Google Drive Refresh Token
google.client.id=${GOOGLE_CLIENT_ID_REFRESH_PROD}
google.client.secret=${GOOGLE_CLIENT_SECRET_REFRESH_PROD}
google.refresh.token=${GOOGLE_REFRESH_TOKEN_PROD}
google.drive.folder.id=${GOOGLE_DRIVE_FOLDER_URL_PROD}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${GOOGLE_USER_EMAIL_PROD}
spring.mail.password=${GOOGLE_APP_EMAIL_PASS_PROD}


# Additional Properties
# Force SSL instead of STARTTLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.debug=true